### ISSUE TITLE
Implement `EmailPlaceholderService`

### ISSUE THREAD

**Issue by Abdurahmon0412** [sulton-max/Training.AirBnb.Clone#12]
### Description
Implement an `EmailPlaceholderService` that builds placeholder collection with values based on given category and user.
This service should use other service to find placeholders from the template and return with values as dictionary with keys

### Requirements
- should build values for placeholder by only requiring category of that email

### Deliverables
- service that creates and returns email placeholder data

**Comment by rashidovasadbek** [comment]
EmailPlaceholderService
