### ISSUE TITLE
Create `UserCredentials` entity

### ISSUE THREAD

**Issue by Ilxom-22** [sulton-max/Training.AirBnb.Clone#209]
## Description
Create `UserCredentials` entity for storing user credentials safely

### Requirements
- project should be runnable

### Deliverables
- `UserCredentials` entity, must be owned type of `User`
- `UserCredentialsConfiguration` entity configuration
- `UserCredentailsRepository` repository
- `UserCredentialsService` foundations service
- fluent validation
- add migration
- register all necessary infrastructure to DI

**Comment by sulton-max** [comment]
Need to find ways to not include user credentials when querying user
